openapi: 3.0.2
info:
  version: 1.0.0
  title: Example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: >
    RDXT casasd
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /echo:
    $ref: paths/echo.yaml
